#!/usr/bin/env python3
"""Generates the iOS startup images, their <link> tags and the manifest icons.

Everything comes from one device table and one mark (scripts/brand-mark.png,
a greyscale coverage mask), so sizes and links can never drift apart. Run it
after changing the table, the mark or the colours, then commit the output:

    pip install pillow
    python3 apps/web/scripts/generate-app-assets.py

Adding a device is one row in DEVICES. Bump SPLASH_VERSION when artwork
changes; existing Home Screen installs keep their old image until re-added.
"""

from pathlib import Path
import re

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
MARK = Image.open(ROOT / "scripts" / "brand-mark.png").convert("L")
SPLASH_DIR = ROOT / "static" / "splash_screens"
ICON_DIR = ROOT / "static" / "icons"
APP_HTML = ROOT / "src" / "app.html"
SPLASH_VERSION = 2

# CSS points, portrait, device pixel ratio. Unique triples only: many models
# share one (see the skill's ios-devices table, checked 2026-09).
DEVICES = [
    (320, 568, 2), (375, 667, 2), (414, 736, 3), (375, 812, 3),
    (414, 896, 2), (414, 896, 3), (390, 844, 3), (428, 926, 3),
    (393, 852, 3), (430, 932, 3), (402, 874, 3), (440, 956, 3),
    (420, 912, 3),
    (768, 1024, 2), (810, 1080, 2), (820, 1180, 2), (744, 1133, 2),
    (834, 1112, 2), (834, 1194, 2), (834, 1210, 2), (1024, 1366, 2),
    (1032, 1376, 2),
]

# Backgrounds match the first rendered <body> (--background in app.css), so
# the splash hands over to the page without a flash; the mark is --foreground.
APPEARANCES = {
    "light": {"bg": (0xF9, 0xF9, 0xF9), "mark": (0x18, 0x18, 0x18)},
    "dark": {"bg": (0x0E, 0x0E, 0x0E), "mark": (0xE5, 0xE5, 0xE5)},
}

# The icon keeps its own dark tile, matching apple-touch-icon.png.
ICON_BG = (0x17, 0x17, 0x17)
ICON_MARK = (0xE5, 0xE5, 0xE5)


def compose(size, bg, fg, mark_width):
    canvas = Image.new("RGB", size, bg)
    w = round(mark_width)
    h = round(MARK.height * w / MARK.width)
    mask = MARK.resize((w, h), Image.LANCZOS)
    canvas.paste(Image.new("RGB", (w, h), fg), ((size[0] - w) // 2, (size[1] - h) // 2), mask)
    return canvas


def splash_mark_points(width, height):
    # About a quarter of the short side on phones, capped on iPads.
    return min(min(width, height) * 0.26, 160)


def generate_splash():
    for old in SPLASH_DIR.glob("*.png"):
        old.unlink()
    links = []
    for width, height, dpr in DEVICES:
        for orientation in ("portrait", "landscape"):
            w, h = (width, height) if orientation == "portrait" else (height, width)
            for scheme, colors in APPEARANCES.items():
                name = f"{width}x{height}@{dpr}-{orientation}-{scheme}.png"
                image = compose((w * dpr, h * dpr), colors["bg"], colors["mark"],
                                splash_mark_points(width, height) * dpr)
                image.save(SPLASH_DIR / name, optimize=True)
                media = (
                    f"(device-width: {w}px) and (device-height: {h}px) and "
                    f"(-webkit-device-pixel-ratio: {dpr}) and (orientation: {orientation}) and "
                    f"(prefers-color-scheme: {scheme})"
                )
                links.append(
                    f'\t\t<link rel="apple-touch-startup-image" media="{media}" '
                    f'href="/splash_screens/{name}?v={SPLASH_VERSION}" />'
                )
    html = APP_HTML.read_text()
    block = "\n".join(["\t\t<!-- splash:start (generated by scripts/generate-app-assets.py) -->", *links, "\t\t<!-- splash:end -->"])
    html, count = re.subn(r"\t*<!-- splash:start.*?<!-- splash:end -->", block, html, flags=re.S)
    if count != 1:
        raise SystemExit("app.html needs one <!-- splash:start --> … <!-- splash:end --> block")
    APP_HTML.write_text(html)
    return len(links)


def generate_icons():
    ICON_DIR.mkdir(exist_ok=True)
    for size in (192, 512):
        # "any": the mark at the touch icon's proportion.
        compose((size, size), ICON_BG, ICON_MARK, size * 0.656).save(ICON_DIR / f"icon-{size}.png", optimize=True)
        # "maskable": inside Android's 80% safe zone.
        compose((size, size), ICON_BG, ICON_MARK, size * 0.5).save(ICON_DIR / f"maskable-{size}.png", optimize=True)


if __name__ == "__main__":
    print(f"{generate_splash()} startup images and links")
    generate_icons()
    print("manifest icons written")
