import type { RequestHandler } from '@sveltejs/kit';
import { SITE_NAME } from '@class-info/backend/convex/config';

// iOS takes the Home Screen name, start URL and display mode from here and
// ignores the colours; Chrome and Android use all of it. The icons are
// generated by scripts/generate-app-assets.py.
export const GET: RequestHandler = () => {
	const manifest = {
		id: '/',
		name: SITE_NAME,
		short_name: SITE_NAME,
		start_url: '/',
		scope: '/',
		display: 'standalone',
		background_color: '#f9f9f9',
		theme_color: '#f9f9f9',
		icons: [
			{ src: '/icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
			{ src: '/icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
			{ src: '/icons/maskable-192.png', sizes: '192x192', type: 'image/png', purpose: 'maskable' },
			{ src: '/icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' }
		]
	};
	return new Response(JSON.stringify(manifest), {
		headers: {
			'Content-Type': 'application/manifest+json; charset=utf-8',
			'Cache-Control': 'public, max-age=3600'
		}
	});
};
